### ISSUE TITLE
Request to provide an English translation of the Data flow diagram

### ISSUE THREAD

**Issue by Anirudh257** [Mostro-Complexity/action-recognition-with-skeleton#1]
Hey, thanks a lot for providing your code and pre-trained model for action recognition. I was trying to understand the Data flow diagram using OCR but it is not being translated properly. It will be great if you could include a Data Flow diagram in English as well.

**Comment by Mostro-Complexity** [comment]
Hello, this is my graduation thesis experiment. In fact, this code is wrong, I chose the wrong classifier (I used the naive Bayes classifier). Welcome to my other project, which has some algorithms that have been implemented.
https://github.com/Mostro-Complexity/action-recognition-survey

**Comment by Anirudh257** [comment]
Thank you so much for replying and providing the new code.
